<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '410b106fcb8e286c3c2040e5508865dd' => $baseDir . '/page-as-term-layout.php',
);
