<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Ramphor\\TermLayout\\' => array($baseDir . '/src'),
    'Jankx\\Abstractions\\' => array($vendorDir . '/jankx/abstractions/src'),
);
